# $ docker run --name my-memcache -d memcached memcached -m 64
---
version: "3.7"

services:
  memcached:
    image: memcached:latest
    container_name: memcached
    # command: ["-m", "1000"] 
    environment:
      - MEMCACHED_MEMORY_LIMIT=1000m
    volumes:
      - memcached:/data
    restart: always
    ports:
        - "11211:11211"

volumes:
  memcached:
