---
version: "3.7"

# common properties
x-common: &common
  tty: true
  stdin_open: true

services:
  filesplit:
    <<: *common
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      # cache dependencies
      - filesplit:/go/pkg/mod
    env_file:
      - env.dev
    depends_on:
      - memcached

  memcached:
    <<: *common
    image: memcached:latest
    container_name: memcached
    # command: ["-m", "1000"] 
    environment:
      - MEMCACHED_MEMORY_LIMIT=1000m
    volumes:
      - memcached:/data
    ports:
        - "11211:11211"

volumes:
  memcached:
  filesplit:
