---
apiVersion: v1
kind: Service
metadata:
  name: aaa
  labels:
    app: aaa
  resourceVersion: "aaa"
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    deploy: aaa
